CREATE DATABASE PHP_SECURITY DEFAULT CHARACTER SET UTF8;

CREATE TABLE TEST_TABLE
(KEY_COLUMN INT
,COLUMN1 VARCHAR(100)
, CONDITION_KEY VARCHAR (100)
, PRIMARY KEY (KEY_COLUMN)) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8;
